
excluded:
  - Pods
  
opt_in_rules:
  # stability
  - force_cast
  - force_try
  - force_unwrapping
  
disabled_rules:
    - trailing_whitespace
    - identifier_name

function_body_length:
    warning: 150
